### ISSUE TITLE
Crisp output cannot be calculated

### ISSUE THREAD

**Issue by DwarakanadhKopuri** [scikit-fuzzy/scikit-fuzzy#185] opened 2018-07-27 05:03 UTC
Pls have a look at my code and suggest me where i went wrong

outputs.input['X1'] = 3
outputs.input['X2'] = 4
outputs.input['X3'] = 5
outputs.input['X4'] = 3
outputs.input['X5'] = 4
outputs.input['X6'] = 5
outputs.input['X7'] = 4
outputs.input['X8'] = 5
outputs.input['X9'] = 3
outputs.input['X10'] = 5
outputs.input['X11'] = 5
outputs.input['X12'] = 4
outputs.input['X13'] = 5
outputs.input['X14'] = 4
outputs.input['X15'] = 3
outputs.input['X16'] = 5
outputs.input['X17'] = 5
outputs.input['X18'] = 4
outputs.input['X19'] = 4
outputs.input['X20'] = 5
outputs.input['X21'] = 3
outputs.input['X22'] = 4
outputs.input['X23'] = 5
outputs.input['X24'] = 4
outputs.input['X25'] = 4
outputs.input['X26'] = 4
outputs.input['X27'] = 3
outputs.input['X28'] = 5
outputs.input['29'] = 5
outputs.input['X40'] = 4
# Crunch the numbers
outputs.compute()

i build different rules but it is only considering rule of one common number why not different number combinations is not accepting??

E:\ProgramData\Anaconda3\lib\site-packages\skfuzzy\control\controlsystem.py in defuzz(self)
    562                               self.var.defuzzify_method)
    563             except AssertionError:
--> 564                 raise ValueError("Crisp output cannot be calculated, likely "
    565                                  "because the system is too sparse. Check to "
    566                                  "make sure this set of input values will "

ValueError: Crisp output cannot be calculated, likely because the system is too sparse. Check to make sure this set of input values will activate at least one connected Term in each Antecedent via the current set of Rules.

**Comment by DwarakanadhKopuri** [comment] 2018-07-27 10:45
Yes , i built rules of 30 variables nearly . Is there any other solution to sort it out sir . Or more configured system is needed to do these ??( My Config Current is -- i5 , processor with 16GB Ram)

**Comment by JDWarner** [comment] 2018-07-27 10:51
This is not an issue of system resources, people run systems with hundreds of rules and variables.

This error happens when people don't fully understand the subtleties of how the rules work.  Every possible set of inputs must trigger at least one Rule.  You may need a surprising number of Rules to ensure that every possible set of inputs will actually do this, particularly if your rules are restrictive (linked with AND).  This error happens when your Rules failed to cover that particular set of inputs - in other words, your set of Rules is too sparse, and failed to cover the entire space of inputs.

I cannot help you debug this further unless you are willing to make the full system available, but I can guarantee this is what's happening.

**Comment by DwarakanadhKopuri** [comment] 2018-07-27 11:06
X1 = ctrl.Antecedent(np.arange(0,6,1),'X1')
X2 = ctrl.Antecedent(np.arange(0,6,1),'X2)
X3 = ctrl.Antecedent(np.arange(0,6,1),'X3')
X4 = ctrl.Antecedent(np.arange(0,6,1),'X4')
X5 = ctrl.Antecedent(np.arange(0,6,1),'X5')
X6 = ctrl.Antecedent(np.arange(0,6,1),'X6')
X7 = ctrl.Antecedent(np.arange(0,6,1),'X7')
X8 = ctrl.Antecedent(np.arange(0,6,1),'X8')
X9 = ctrl.Antecedent(np.arange(0,6,1),'X9')
X10 = ctrl.Antecedent(np.arange(0,6,1),'X10')
X11 = ctrl.Antecedent(np.arange(0,6,1),'X11')
X12 = ctrl.Antecedent(np.arange(0,6,1),'X12')
X13 = ctrl.Antecedent(np.arange(0,6,1),'X13')
X14 = ctrl.Antecedent(np.arange(0,6,1),'X14')
X15 = ctrl.Antecedent(np.arange(0,6,1),'X15')
X16 = ctrl.Antecedent(np.arange(0,6,1),'X16')
X17 = ctrl.Antecedent(np.arange(0,6,1),'X17')
X18 = ctrl.Antecedent(np.arange(0,6,1),'X18')
X19 = ctrl.Antecedent(np.arange(0,6,1),'X19')
X20 = ctrl.Antecedent(np.arange(0,6,1),'X20')
X21= ctrl.Antecedent(np.arange(0,6,1),'X21')
X22 = ctrl.Antecedent(np.arange(0,6,1),'X22')
X23 = ctrl.Antecedent(np.arange(0,6,1),'X23')
X24 = ctrl.Antecedent(np.arange(0,6,1),'X24')
X25= ctrl.Antecedent(np.arange(0,6,1),'X25')
X26 = ctrl.Antecedent(np.arange(0,6,1),'X26')
X27 = ctrl.Antecedent(np.arange(0,6,1),X27')
X28 = ctrl.Antecedent(np.arange(0,6,1),'X28')
X29 = ctrl.Antecedent(np.arange(0,6,1),'X29')
X30 = ctrl.Antecedent(np.arange(0,6,1),'RecommendsschoolX30')


Rate = ctrl.Consequent(np.arange(0, 26, 1), 'Rate')

Sir , as these are my inputs which is in between (0 to 5 Range value ) . Just like the tipping problem

import skfuzzy as fuzz
Rate['poor'] = fuzz.trimf(Rate.universe, [0, 0, 10])
Rate['Average'] = fuzz.trimf(Rate.universe, [0, 10, 25])
Rate['good'] = fuzz.trimf(Rate.universe, [10, 25, 25])

rule1 = ctrl.Rule(X1['poor'] &X2['poor'] & X3['poor'] & X4['poor'] & X5['poor'] &X6['poor'] & X7['poor'] & X8['poor'] & X9['poor'] & X10['poor'] & X11['poor'] ..like this these goes for 30variables with [Poor} as one . 

rule2 = same as above with X1 ,X2 ,X3..with[average] ..as one 

rule 3 = same as rule1 with [good]

any suggestions pls let me know sir i need support

**Comment by JDWarner** [comment] 2018-07-27 13:00
I do not think you understand what I said above about a sparse system and restrictive rules.

When you unite all of the Terms in one Rule with AND (&), that Rule will ONLY EVER fire if ALL of the conditions are satisfied.  Otherwise it has no output!  The system is trying to tell you this.

The approach you describe, handling 30 variables with 3 rules - all of which are united with AND - is an extremely sparse set of rules.  The only values the system can actually compute are for values where literally every variable is close to poor, every variable is close to average, or every variable is close to good.

You must create a much more in dept set of rules, or combine your rules with OR (|) rather than AND, in order to make this work.

Closing as resolved and not a bug.

**Closed by JDWarner** 2018-07-27 13:00 UTC
