### ISSUE TITLE
NameError: name 'version' is not defined

### ISSUE THREAD

**Issue by brunobro** [scikit-fuzzy/scikit-fuzzy#87] opened 2016-03-24 10:55 UTC
I installed as: pip install -U scikit-fuzzy. 

When "import skfuzzy as fuzz" gives error:

**NameError: name 'version' is not defined**

My system: ubuntu 14.04 LTS; python2.7

**Comment by JDWarner** [comment] 2016-03-24 12:45
The version file is created during a successful installation; this error indicates that either 

* the pip installation had a problem or 
* your PYTHONPATH points to a source version which has not been installed before the installed version

First try reinstalling. `pip uninstall scikit-fuzzy` followed by the first command again. Pay attention to the installation log, and if anything seems amiss paste the log here.

**Comment by brunobro** [comment] 2016-03-24 14:03
I installed the package without errors in the pip install, but the error keeps:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/bruno/PESQUISAS/AGRICULTURA/scripts/fuzzy.py", line 10, in <module>
    import skfuzzy as fuzz
  File "/usr/local/lib/python2.7/dist-packages/skfuzzy/__init__.py", line 22, in <module>
    del version
NameError: name 'version' is not defined

**Comment by nilayrox18** [comment] 2016-03-24 14:13
sir we are trying to install a  Networkx and scikit-fuzzy for a Rasbeery Pi
2. but it shows error please sir resolve this problem we wamt advance
scikit fuzzy moduel in which you provide controls too.

On Thu, Mar 24, 2016 at 7:33 PM, brunobro <notifications@github.com> wrote:

> I installed the package without errors in the pip install, but the error
> keeps:
>
> Traceback (most recent call last):
> File "", line 1, in
> File
> "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py",
> line 540, in runfile
> execfile(filename, namespace)
> File "/home/bruno/PESQUISAS/AGRICULTURA/scripts/fuzzy.py", line 10, in
> import skfuzzy as fuzz
> File "/usr/local/lib/python2.7/dist-packages/skfuzzy/*init*.py", line 22,
> in
> del version
> NameError: name 'version' is not defined
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scikit-fuzzy/scikit-fuzzy/issues/87#issuecomment-200851399>
>



-- 
*Mr. Nilay S. Shah*
*M.Tech ICT  *
*Contact no : +91-8866319714*

**Comment by JDWarner** [comment] 2016-03-24 14:58
Please raise a separate Issue regarding Raspberry Pi installation from
source, including what you've tried and where you seem to be stuck. That is
a separate problem.

I will be deleting both of these messages in a few hours to keep this Issue
clean.

**Comment by brunobro** [comment] 2016-03-24 16:02
Dear JDWarner. My messenge is related the execution scikit-fuzzy:

File "/home/bruno/PESQUISAS/AGRICULTURA/scripts/fuzzy.py", line 10, in 
import skfuzzy as fuzz
File "/usr/local/lib/python2.7/dist-packages/skfuzzy/init.py", line 22, in 
del version
NameError: name 'version' is not defined

**Comment by JDWarner** [comment] 2016-03-25 03:40
I can't reproduce this with my Python configurations, however, I do see scattered reports of something like it. From what I gather, it is likely a permissions issue with the separate file `version.py` which periodically crops up when using system Python installations. The fix should be relatively straightforward...

**Comment by JDWarner** [comment] 2016-03-25 05:38
@brunobro, please try updating your installation. I am hopeful version 0.1.9 from PyPi (solution method in #89) will solve this.

**Comment by brunobro** [comment] 2016-03-25 10:09
Thanks. The problem was resolved. 

But other problem it occurred: [https://github.com/scikit-fuzzy/scikit-fuzzy/issues/90](https://github.com/scikit-fuzzy/scikit-fuzzy/issues/90)

**Comment by JDWarner** [comment] 2016-03-25 12:26
Closing as resolved

**Closed by JDWarner** 2016-03-25 12:26 UTC
