### ISSUE TITLE
TypeError: '<=' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by charmowen** [scikit-fuzzy/scikit-fuzzy#275] opened 2020-11-09 08:20 UTC
>>> skfuzzy.__version__
'0.4.2'
 ---------------------------------------------------------------------------------------------------------------------------------
   self.sim.compute()  
  File "D:\miniconda\envs\pyfuzzy\lib\site-packages\skfuzzy\control\controlsystem.py", line 368, in compute
    self.compute_rule(rule)
  File "D:\miniconda\envs\pyfuzzy\lib\site-packages\skfuzzy\control\controlsystem.py", line 405, in compute_rule
    rule.aggregate_firing[self] = rule.antecedent.membership_value[self]
  File "D:\miniconda\envs\pyfuzzy\lib\site-packages\skfuzzy\control\term.py", line 141, in __getitem__
    term1 = self.agg.term1.membership_value[key]
  File "D:\miniconda\envs\pyfuzzy\lib\site-packages\skfuzzy\control\term.py", line 143, in __getitem__
    term2 = self.agg.term2.membership_value[key]
  File "D:\miniconda\envs\pyfuzzy\lib\site-packages\skfuzzy\control\term.py", line 149, in __getitem__
    return self.agg.agg_methods.and_func(term1, term2)
TypeError: '<=' not supported between instances of 'NoneType' and 'float'
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by scikit-fuzzy** [comment] 2020-11-09 11:02
Going to need full context here, as it looks like improper use - one of
your terms/arguments is `None`.

**Comment by charmowen** [comment] 2020-11-10 09:47
When I loop the program for a long time, the value on the ControlSystemSimulation address is lost

**Comment by JDWarner** [comment] 2021-11-09 05:28
I'm provisionally closing this but if you could possibly provide a full reproducible example - ideally alongside `conda list` for the offending environment - it can be reopened.

I am fairly sure nothing Scikit-Fuzzy is doing could produce this (loss of memory address).  Scikit-Fuzzy is pure Python so it's either configuration or something on that hardware, an error in Python's GIL, or an error in NumPy memory handling.

**Closed by JDWarner** 2021-11-09 05:28 UTC
