### ISSUE TITLE
skfuzzy.Antecedents not working!!!

### ISSUE THREAD

**Issue by nikhrao** [scikit-fuzzy/scikit-fuzzy#107] opened 2016-06-13 10:05 UTC
Traceback (most recent call last):
  File "FCS.py", line 9, in <module>
    quality = skfuzzy.Antecedent(np.arange(0, 11, 1), 'quality')
AttributeError: 'module' object has no attribute 'Antecedent'

Can anyone resolve this issue

**Comment by JDWarner** [comment] 2016-06-13 16:21
We cleaned the namespace. All new API classes must now be accessed/imported
through fuzz.control rather than from fuzz.

You can also `import fuzz.control as ctrl` and then use ctrl for a shorter
prefix.

The reason is to keep all of the new functionality together, so people can
more easily use and explore pieces of the new API.

**Comment by JDWarner** [comment] 2016-06-13 16:24
Closing as intended behavior, with explanation above on how to address the problem for pre-0.2 code.

**Closed by JDWarner** 2016-06-13 16:24 UTC

**Comment by nikhrao** [comment] 2016-06-13 16:25
Thank you !! Will try that will get back if any issues

**Comment by rddspatial** [comment] 2020-07-11 14:02
I am getting the following error. How to resolve this?

  File "/opt/anaconda3/lib/python3.7/site-packages/skfuzzy/control/controlsystem.py", line 430, in compute_rule
    accu = term.parent.accumulation_method

AttributeError: 'Antecedent' object has no attribute 'accumulation_method'
