### ISSUE TITLE
Wrong Trapezoid-Shaped Membership Function with point numbers

### ISSUE THREAD

**Issue by w-harter** [scikit-fuzzy/scikit-fuzzy#163] opened 2018-01-10 16:11 UTC
Hello,

I got a problem while using point numbers for declaring trapezoid-shaped membership functions (as you can see on the attached screenshots).

**With point numbers (look at the green membership function):**
![01](https://user-images.githubusercontent.com/33289962/34782156-17f03272-f628-11e7-9f39-1d0d0443a6b2.PNG)

speed_95_lo = fuzz.trapmf(speed_95, [-1, 0, 6, 8])
speed_95_md = fuzz.trapmf(speed_95, [**7.5**, **9.5**, 15, 18])
speed_95_hi = fuzz.trapmf(speed_95, [15, 20, 22, 23])

**Without point numbers:**
![02](https://user-images.githubusercontent.com/33289962/34782220-4edd14a8-f628-11e7-9bcf-4c723ee5c3c3.PNG)
speed_95_lo = fuzz.trapmf(speed_95, [-1, 0, 6, 8])
speed_95_md = fuzz.trapmf(speed_95, [**7**, **9**, 15, 18])
speed_95_hi = fuzz.trapmf(speed_95, [15, 20, 22, 23])

I hope I have just overlooked a small thing... Does anyone have a tip or ever had the same problem?

Thanks!

**Comment by JDWarner** [comment] 2018-01-11 05:40
While not necessarily intuitive, this is working as intended.

Not shown is when you define the universe `speed_95`, but I can presume it contains integer numbers from at least -1 through 23.  When you do that, you create a discrete universe on which everything else will be sampled.

When you then define membership functions using key points _which are not included in your universe_, those points are not added to the universe.  The universe points _which do exist_, are evaluated against the function you said you _wanted_.  All of the values are correct, but because the key points aren't there when you connect the dots you see discontinuities.  It's a classic discrete-vs-continuous system issue.

You are probably asking 'how can I avoid this?'

Well, fortunately it turns out scikit-fuzzy accepts and even thrives on sparse systems.  Some forethought when you create your system completely avoids this, and makes everything run faster to boot.  A sparse system has only the key anchor points necessary for your membership functions _and no more_.  You do not need to use a dense universe (e.g., [1, 2, 3, 4, 5, 6, 7]); any collection of ordered points will do.  If your system's membership functions only need 1, 1.5, `np.pi`, 4, 7, and 9 you should define your universe as [1, 1.5, `np.pi`, 4, 7, 9].

Put to practice, in your above examples it looks like `speed_95` should be simply [0, 6, 7.5, 8, 9.5, 10, 15, 18, 20, 22, 23] for the first example, and [0, 6, 7, 8, 9, 10, 15, 18, 20, 22, 23] for the second.

Furthermore, because the system has to calculate on the basis of every point in the universe for every result, making the universe maximally sparse in this way greatly improves the efficiency of each simulation computation.

I should assure you that it is perfectly fine to evaluate the system with arbitrary inputs, between universe values, and you get correct results.  This effect is only for the universe and your membership functions. Put simply, universe(s) _must_ include all key inflection points for your membership functions - and ideally no more.

Closing as resolved, but feel free to comment further if that was unclear.

**Closed by JDWarner** 2018-01-11 05:40 UTC

**Comment by w-harter** [comment] 2018-01-11 09:28
Thanks a lot! I got the right membership functions now.

Like you said - although not necessarily intuitive, it now makes sense.
