### ISSUE TITLE
Plotting problem

### ISSUE THREAD

**Issue by andressotov** [scikit-fuzzy/scikit-fuzzy#135] opened 2017-05-10 07:57 UTC
Hi,
I am using Python 3.5.2 
First I tried plot_tipping_problem.py, but I had a plotting problem: it doesn't show nothing. So I decided to insert a plt.show() at the end and it works for me. 
Now I am trying plot_tipping_problem_newappi.py and I have a similar problem: it doesn't show any figure, although it prints the tip at the end (I had to put the prints argument inside parethesis, but this is because of the Python version). The situation is that I can't use the same solution, plt.show(), to see the figures because it is not using matplotlib. What can I do?
Thank you in advance
Andres

**Comment by JDWarner** [comment] 2017-05-10 12:13
The new API most assuredly is using matplotlib under the hood.  I'm surprised a plt.show() isn't giving you anything at all.  

Have you tried running the examples from a Jupyter notebook?

**Comment by andressotov** [comment] 2017-05-10 12:25
Maybe I didn't explain myself well. I ran the two tip examples. With the hard one, at first moment, I didn't obtain any figure. Then I included a call to plt.show() and it gave me the figures. But, with the tip example using the API, Matplotlib is not imported (at least, in this code), so I can not call to plt.show(). At the same time, .view() doesn't show nothingI am using PyCharm Community Edition 2017.1.2. I have not tried with a Jupyter notebook. Andrés Soto

**Comment by JDWarner** [comment] 2017-05-10 12:44
Ah.  Import Matplotlib before you run it, then call plt.show.  Matplotlib
is imported within the appropriate control functions/classes.

You're not the first to ask questions about the view methods.  Version 0.3
will be out shortly, and it will have some plotting improvements.  In
short, the reason you have to manually show the plots is so the actual plot
objects are available for further customization by users.

**Comment by andressotov** [comment] 2017-05-10 15:45
Great, it works! Thanks! Is it (or it would be) possible to use the graph and operate with the nodes? Can I get information about each node? Or interact with them in some way?Best Andrés Soto

**Comment by JDWarner** [comment] 2017-05-11 21:21
The entire control submodule is built upon a directed NetworkX graph.  This graph is quite a powerful object, but NetworkX has limited visualization options available.  

If you would like to directly access this, it is publicly exposed as ControlSystem.graph or ControlSystemSimulation.ctrl.graph

**Comment by Raphango** [comment] 2018-01-22 22:53
I had this same problem loading the .py file at the console. At the tipping problem example, I saw that were some very brief apparitions of which seemed like matplotlib windows.
In order to really show the graphs, I had to import matplotlib.pyplot as plt and use plt.show() after each *.view() method.

Maybe everybody that doesn't use Ipython/Jupyter notebooks is having the same problem.

By the way, at the example the final returned value has still to be corrected (19.847607362 instead of 20.64).

But, after all, congratulations for your great work!! =)

**Comment by JDWarner** [comment] 2018-01-23 01:42
@Raphango, there's a tension here between maximizing convenience and optimizing the power exposed.  When dealing with Matplotlib figures, particularly if anyone needs to restyle them or tweak things further, they actually need the `Figure` and `Axis` objects - not just the plot.  A conscious decision was made to allow anyone to take these outputs and use them further for their own purposes, rather than just run `plt.show()` internally and return nothing.

This does mean you need to manually ask for the figures when you want them, with `plt.show()`, and that's by design.  It may seem not ideal right now, but if you ever take one of these plots and need it at a different resolution or something for a paper, you'll thank me ;)

The hardcoded result in the example has been corrected in the codebase as of 51f9f4d in #162.

Closing as wontfix, with hopefully well-justified reasons for the current API.

**Closed by JDWarner** 2018-01-23 01:42 UTC
