### ISSUE TITLE
 Scikit 0.3 AttributeError

### ISSUE THREAD

**Issue by EmmyGuy** [scikit-fuzzy/scikit-fuzzy#149] opened 2017-09-24 15:37 UTC
Hi everyone.
On trying to implement the tipping example of the scikit version 0.3, I get this error from exactly the command thus:
tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3]) gives:
Traceback (most recent call last):

  File "<ipython-input-5-3c5b2551db94>", line 1, in <module>
    runfile('C:/Python27/Lib/site-packages/skfuzzy/control/tipping.py', wdir='C:/Python27/Lib/site-packages/skfuzzy/control')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Python27/Lib/site-packages/skfuzzy/control/tipping.py", line 41, in <module>
    tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

  File "C:\Python27\lib\site-packages\skfuzzy\control\controlsystem.py", line 45, in __init__
    self.addrule(rule)

  File "C:\Python27\lib\site-packages\skfuzzy\control\controlsystem.py", line 98, in addrule
    for r in self.rules:

  File "C:\Python27\lib\site-packages\skfuzzy\control\controlsystem.py", line 596, in __iter__
    self._cache = list(self._process_rules(self.all_rules[:]))

  File "C:\Python27\lib\site-packages\skfuzzy\control\controlsystem.py", line 630, in _process_rules
    if self._can_calc_rule(rule):

  File "C:\Python27\lib\site-packages\skfuzzy\control\controlsystem.py", line 658, in _can_calc_rule
    for p in self.all_graph.predecessors_iter(rule):

AttributeError: 'DiGraph' object has no attribute 'predecessors_iter'

**Comment by JDWarner** [comment] 2017-09-24 16:06
Thanks for reporting, @EmmyGuy - can you check what version of NetworkX you are running?  I suspect version 2, which was just released with some API changes, and that we'll need to ship a bugfix release because of it.

**Comment by JDWarner** [comment] 2017-09-24 21:57
I can reproduce after upgrading to NetworkX 2.0, this is definitely the source of the problem.  Looking for the best workaround.

**Comment by EmmyGuy** [comment] 2017-09-25 09:49
You are right Josh, am running version 2.0 of networkx.

One more thing; i don't know if the skfuzzy  API implements other forms of
membership function aside the generic triangular membership function as
seen on the tutorial?

**Comment by JDWarner** [comment] 2017-09-26 06:27
@EmmyGuy I have a workaround that seems fine, but is failing a rather subtle test or it'd be up already.

skfuzzy supports literally any membership function you can imagine.  The `automf` method is really handy to make families of triangular shaped membership functions, but you can add your own interactively using any membership function you care to define - so long as it's on the same universe the fuzzy variable expects.  So long as it's on the same universe and the values are between 0 and 1, it'll work.

**Comment by EmmyGuy** [comment] 2017-09-26 09:25
Ok @JDWarner; thanks for the effort. will be glad to see it work.
On the membership-function thing, I will try the **trapezoidal** membership function.

thanks

**Comment by EmmyGuy** [comment] 2017-09-28 09:31
Hello @JDWarner. please i don't know if you have any solution yet for the bug? Else, i'd appreciate any suggestion you can offer. 

Thanks.

**Comment by EmmyGuy** [comment] 2017-10-04 09:33
Thanks @JDWarner; the fix really is helping me out.

**Comment by JDWarner** [comment] 2017-10-06 05:49
Closed by #150.

**Closed by JDWarner** 2017-10-06 05:49 UTC
