### ISSUE TITLE
Colors of all clusters are uniform

### ISSUE THREAD

**Issue by redfoxufa** [scikit-fuzzy/scikit-fuzzy#80] opened 2016-02-23 18:54 UTC
When I run the example 'Fuzzy c-means clustering' in the first step I get three color dots (orange, green and blue), but in the next steps all dots are blue(((

**Comment by JDWarner** [comment] 2016-02-24 04:27
Having trouble reproducing this. 

I just re-tested with the latest stable releases of everything scikit-fuzzy depends on in the Anaconda stack. The results I'm getting [are exactly as shown in the docs here](http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_cmeans.html).

Can you check your matplotlib version? The only other thing that comes to mind is that the colors in this example depend on matplotlib's default color cycling. If you have custom matplotlib parameters set, or have set a custom color cycler, that could explain the difference.

If not, please give some more information about your system and what versions of Python, scikit-fuzzy, and matplotlib you're running.

**Comment by redfoxufa** [comment] 2016-02-24 17:55
Dear JDWarner,
I use Ubuntu 15.10 and Pycharm Comunity Edition 5.0.4. I have updated matplotlib with following comand:
sudo apt-get build-dep python-matplotlib
Then I have opend the link 'http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_cmeans.html'
I have copied a block 'Data generation and setup' into the PyCharm. That's all right. I have three colored dots. But following blocks of code: 'Clustering', 'The fuzzy partition coefficient (FPC)', 'Classifying New Data' and 'Prediction' gives me a blue dots. Can you help me?
With best regards, Marat

**Comment by jsexauer** [comment] 2016-02-27 22:13
I have no clue what could cause this.  Can you verify that the colors list isn't somehow getting modified by adding `print(colors)` after each section?

**Comment by redfoxufa** [comment] 2016-03-02 13:42
Dear Josh,
I have inserted a print statement between blocks.
Can you look at results?
Marat

Python version 3.4.4 |Anaconda 2.3.0 (64-bit)| (default, Jan 11 2016,
13:54:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Pandas version 0.17.1
Matplotlib version 1.4.3


['b', 'orange', 'g', 'r', 'c', 'm', 'y', 'k', 'Brown', 'ForestGreen']
['b', 'orange', 'g', 'r', 'c', 'm', 'y', 'k', 'Brown', 'ForestGreen']
['b', 'orange', 'g', 'r', 'c', 'm', 'y', 'k', 'Brown', 'ForestGreen']
['b', 'orange', 'g', 'r', 'c', 'm', 'y', 'k', 'Brown', 'ForestGreen']

2016-02-24 9:27 GMT+05:00 Josh Warner <notifications@github.com>:

**Comment by jsexauer** [comment] 2016-03-05 19:09
Looks like it should.  I'm sorry, I'm not sure what could be going on either.

**Comment by JDWarner** [comment] 2016-03-05 19:30
At this point I'm relatively confident it isn't the script or scikit-fuzzy causing the problem. I've verified the correct behavior in Python 2/3, on three separate operating systems (Win7, OSX, Linux Mint). 

I suspect an issue with how matplotlib is installed or configured, and this may not be the ideal place to troubleshoot it. If we can't get to the bottom of this here you may need to raise an issue with matplotlib.

Do you see this with _any_ other Matplotlib figures? If so, can you make a small example of another instance where the `color=` kwarg seems to be ignored? 

You could also try installing a scientific Python distribution like Anaconda, after which I expect this problem would disappear.

**Comment by redfoxufa** [comment] 2016-03-06 08:25
Thank you so much for your patience)))
Marat

2016-03-06 0:09 GMT+05:00 jsexauer <notifications@github.com>:

**Comment by JDWarner** [comment] 2016-03-11 17:58
Closing this as we cannot reproduce the problem. If you solve this, @redfoxufa, please post the solution and cause!

For posterity, as a workaround to future readers, this behavior is _definitely absent_ in Python distributions like Anaconda, Python(x,y), and Canopy. A clean install and fresh virtual environment should result in the expected color behavior in all cases.

**Closed by JDWarner** 2016-03-11 17:58 UTC
Labels: cant-reproduce
