### ISSUE TITLE
import error on raspi OS with python 3.9

### ISSUE THREAD

**Issue by martinklein** [scikit-fuzzy/scikit-fuzzy#287] opened 2022-03-01 17:43 UTC
Installed scikit-fuzzy with
`pip install -U scikit-fuzzy`
on a Raspi OS with all updates installed and on Python 3.9

In my python code I got error when importing skfuzzy:

```
Python 3.9.2 (/usr/bin/python3)
>>> %Run hvac_led_celsius.py
Traceback (most recent call last):
  File "/home/pi/Prolog/hvac_led_celsius.py", line 2, in <module>
    import skfuzzy as fuzz
  File "/home/pi/.local/lib/python3.9/site-packages/skfuzzy/__init__.py", line 24, in <module>
    import skfuzzy.fuzzymath as _fuzzymath
  File "/home/pi/.local/lib/python3.9/site-packages/skfuzzy/fuzzymath/__init__.py", line 44, in <module>
    from ._continuous_to_discrete import continuous_to_discrete
  File "/home/pi/.local/lib/python3.9/site-packages/skfuzzy/fuzzymath/_continuous_to_discrete.py", line 1, in <module>
    import scipy.linalg
  File "/home/pi/.local/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 198, in <module>
    from ._misc import *
  File "/home/pi/.local/lib/python3.9/site-packages/scipy/linalg/_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/home/pi/.local/lib/python3.9/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
```

Many thanks for your help
Martin Klein

**Comment by JDWarner** [comment] 2022-03-01 19:09
The traceback flows from scikit-fuzzy to SciPy where eventually it cannot find a key component of BLAS.  The problem is thus a broken installation of SciPy and its underlying BLAS library.  Consider updating or reinstalling SciPy.  Once you can run `import scipy.linalg` without getting this traceback, try scikit-fuzzy again.  Once corrected, I expect scikit-fuzzy will work normally.

Closing as out of scope for now; if once scipy is fixed you have other issues feel free to open a new Issue.

**Closed by JDWarner** 2022-03-01 19:09 UTC
