### ISSUE TITLE
ValueError: object of too small depth for desired array

### ISSUE THREAD

**Issue by Imane0** [scikit-fuzzy/scikit-fuzzy#179] opened 2018-05-16 11:50 UTC
Hi all!

I am trying to categorize continuous variables using three gaussians with shifted means and same variance. In one of my examples I have the following universe values:
```
In [2]: feat_universe = [-9, 0, 0, -4, 4, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0
   ...: , 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   ...: , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   ...: , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   ...: , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   ...: , 0, 0, 0, 0, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   ...: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   ...: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   ...: 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   ...:  0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4, 4, 0, 0, 0, 0, 0, 0, 0, -2, 
   ...: 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   ...: 0, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   ...:  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3, 8, 4, -13,
   ...:  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   ...:  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   ...:  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   ...:  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
   ...: feat_point = -4 
   ...: feat_name = 'feature_X'
```

The code below is supposed to return a fuzzy variable (either 'small', 'normal', or 'large') for the value `feat_point`. The code works in general, but with the variables above, it raises a `ValueError` (at command [16]; see below). It's eventually a `numpy` error, but I did not find any useful posts when googling. Can it be because the universe values seems dicrete ?

```
In [6]: from skfuzzy.control.fuzzyvariable import FuzzyVariable

In [7]: import skfuzzy

In [8]: fuzzy_var = FuzzyVariable(feat_universe, feat_name)

In [9]: mu = np.mean(feat_universe)
In [12]: sigma = np.std(feat_universe)

In [13]: fuzzy_var['small'] = skfuzzy.gaussmf(feat_universe, mu-sigma, sigma)

In [14]: fuzzy_var['normal'] = skfuzzy.gaussmf(feat_universe, mu, sigma)

In [15]: fuzzy_var['large'] = skfuzzy.gaussmf(feat_universe, mu+sigma, sigma)

In [16]: small_v = skfuzzy.interp_membership(feat_universe, fuzzy_var['small'], feat_point) 
normal_v = skfuzzy.interp_membership(feat_universe, fuzzy_var['normal'], feat_point)
large_v = skfuzzy.interp_membership(feat_universe, fuzzy_var['large'], feat_point)
fuzzy_val = np.argmax([small_v, normal_v, large_v])
names=['small', 'normal', 'large']
fuzzy_val = names[fuzzy_val]

**output:** 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-c0e7bc48c82f> in <module>()
----> 1 small_v = skfuzzy.interp_membership(feat_universe, fuzzy_var['small'], feat_point)

~/anaconda3/lib/python3.6/site-packages/skfuzzy/fuzzymath/fuzzy_ops.py in interp_membership(x, xmf, xx, zero_outside_x)
    656     else:
    657         kwargs = (0.0, 0.0)
--> 658     return np.interp(xx, x, xmf, left=kwargs[0], right=kwargs[1])
    659 
    660 

~/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py in interp(x, xp, fp, left, right, period)
   2055     if period is None:
   2056         if isinstance(x, (float, int, number)):
-> 2057             return interp_func([x], xp, fp, left, right).item()
   2058         elif isinstance(x, np.ndarray) and x.ndim == 0:
   2059             return interp_func([x], xp, fp, left, right).item()

ValueError: object of too small depth for desired array
```

I am using Anaconda with:
- Python 3.6.4
- Numpy 1.14.1

**Comment by Imane0** [comment] 2018-05-16 13:16
Waiting for a solve, I am replacing command [16] with : 
`small_v = gaussian(feat_point, mu-sigma, sigma)`
where:
```
def gaussian(x, mu, sig):
    return np.exp(-np.power(x - mu, 2.) / (2 * np.power(sig, 2.)))
```
I do the same for `normal_v` and `large_v`, and continue with the code as it is.

**Comment by JDWarner** [comment] 2018-07-20 03:42
If I'm reading this right, the array you have defined for the universe is not a correct fuzzy universe.  Fuzzy universes can be piecewise continuous, it's perfectly fine if they jump, but a core assumption is that they are monotonic.  The actual fuzzy membership can then bounce around all it likes, but it should be on the range [0, 1].  The variable `feat_universe` shown is not correct for a universe, nor as a membership function - but then it appears to be used both as universe and membership.

The reason interpolation fails is because the universe is both sparse and very much not monotonic, with many possible points where the interpolation could be true.  Under the monotonic assumption, there should only ever be one point where the requested value can be interpolated.

**Comment by JDWarner** [comment] 2018-11-23 18:14
Closing, addressed (not a bug, misconfigured universe)

**Closed by JDWarner** 2018-11-23 18:14 UTC
