### ISSUE TITLE
manual vs automatic rules discrepancy

### ISSUE THREAD

**Issue by Smrkc** [scikit-fuzzy/scikit-fuzzy#167] opened 2018-02-11 16:00 UTC
I am recieving an error that I cannot make sense of:
RuntimeError: Unable to resolve rule execution order. The most likely reason is two or more rules that depend on each other.
Please check the rule graph for loops.

The error occurs when defining control system:
control_system = ctrl.ControlSystem(controls)

I have a system of 6 antecedents with various number of membership functions and 6 consequents with two states - good and bad. To minimize cognitive load when defining rules I've created a function that parses rule strings. I am combining membership functions because my "bad" rules are defined as inverse of "good" rules.

The function:

def parse_rule(string, antecedents):
    
    def combine_memberships(string):
        subs = string.split("/")    
        for ant in antecedents:
            if subs[0] in ant.terms:
                if len(subs) > 1:
                    ant[string] = reduce(lambda x, y: fuzz.fuzzy_or(ant.universe, x, ant.universe, y)[1], 
                                              [ant[sub].mf for sub in subs])
                    return ant[string]
                else:
                    return ant[string]
    
    options = string.split("_")
    rules = reduce(lambda x, y: x & y, [combine_memberships(option) for option in options])
    return rules

Simplified example rules:

antecedents = [ant1, ant2]
rule1 =ctrl.Rule(antecedent=(parse_rule("A/B_c", antecedents)), 
                         consequent=my_consequent["good"])
rule2 =ctrl.Rule(antecedent=(parse_rule("A/B_d", antecedents)), 
                         consequent=my_consequent["good"])

Note that following instantiation of rules do not produce above mentioned error:
rule3 =ctrl.Rule(antecedent=(ant1["A/B"] & ant2["c"]), 
                         consequent=my_consequent["good"])
rule4 =ctrl.Rule(antecedent=(ant1["A/B"] & ant2["d"]), 
                         consequent=my_consequent["good"])

Note as well that rule1.antecedent and rule3.antecedent are exactly the same. Same goes for rule2 and rule4.

Is this a bug? How can I make it work?

**Comment by Smrkc** [comment] 2018-02-12 09:05
Update:
Reversing order of membership functions does the trick, so I think there is definitely a bug. For example changing "A/B_d" to "B/A_d" works.

rule1 =ctrl.Rule(antecedent=(parse_rule("A/B_c", antecedents)),
consequent=my_consequent["good"])
rule2 =ctrl.Rule(antecedent=(parse_rule("B/A_d", antecedents)),
consequent=my_consequent["good"])

**Comment by Smrkc** [comment] 2018-02-12 09:37
The whole issue seems to be with defining membership functions on the fly, in the process of creating rules. If membership functions are created beforehand, the system seems to work OK. I have verified this on a simple example.

So instead of an issue, this is a candidate for enhancement.

**Comment by JDWarner** [comment] 2018-02-13 00:04
Thanks for the report, @Smrkc.  

The rule order check has to do with circular paths in the graph, and/or the possibility to end up in a position where the actual graph cannot be further traversed in computation.

There was once a check for this.  It worked well in NetworkX 1.x.  Unfortunately, in NetworkX 2.x, things changed and I couldn't break the new system.  The old edge case passed without fail; every example I could come up with did too.

If you could share it, I'd love to see a self-contained example with your entire system - particularly where this breaks and you get the error - in hopes I can use it to fix lingering issues and/or design a new test case.  This is a difficult to reproduce problem, and if you could share it would be greatly appreciated!

**Comment by Smrkc** [comment] 2018-02-13 08:44
Simple example can be found here:
https://github.com/Smrkc/skfuzzy_rule_execution/blob/master/skfuzzy%20test.ipynb

**Comment by JDWarner** [comment] 2018-11-23 22:30
Sorry for the long delay in follow-up.  I see what you mean.

What seems to be happening is a disagreement in the underlying NetworkX graph if Terms are created on-the-fly in this way.

The recommendation and workaround - as you have identified - is to fully define the Terms for a given Antecedent before you add any of those Terms to Rules.  I do not have a simple fix for this, as it touches both the machinery to check rule execution as well as the underlying NetworkX Graph.

**Closed by JDWarner** 2018-11-23 22:30 UTC
